import { Inter } from "next/font/google";
import { Global } from "@emotion/react";
import classNames from "@/styles/emotion/classNames";
import "../styles/globals.scss";

//icon
import { library } from "@fortawesome/fontawesome-svg-core";
import { faCommentDots } from "@fortawesome/free-regular-svg-icons";
library.add(faCommentDots);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <Global styles={classNames} />
      <Component {...pageProps}></Component>
    </>
  );
}
